resources:
- ../../../rbac
- ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: ofen-


transformers:
- label-transformer.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: '{{ include "ofen.name" . }}'
