apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: '{{ .Release.Namespace }}'
resources:
- ../../../rbac
- ../../../webhook


namePrefix: ofen-
transformers:
- label-transformer.yaml
patches:
- path: webhookcainjection-patch.yaml
