apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../crd
transformers:
  - label-transformer.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: ofen
