// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ImageSetApplyConfiguration represents a declarative configuration of the ImageSet type for use
// with apply.
type ImageSetApplyConfiguration struct {
	Image *string `json:"image,omitempty"`
}

// ImageSetApplyConfiguration constructs a declarative configuration of the ImageSet type for use with
// apply.
func ImageSet() *ImageSetApplyConfiguration {
	return &ImageSetApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *ImageSetApplyConfiguration) WithImage(value string) *ImageSetApplyConfiguration {
	b.Image = &value
	return b
}
